const API="https://moodmatch-api-ko99.vercel.app/api/cinemap";
const IMG="https://image.tmdb.org/t/p/w500";
const svg=document.getElementById("graph"),viewport=document.getElementById("viewport"),regionsLayer=document.getElementById("regionsLayer"),edgesLayer=document.getElementById("edgesLayer"),nodesLayer=document.getElementById("nodesLayer"),stats=document.getElementById("mapStats"),drawer=document.getElementById("drawer"),drawerContent=document.getElementById("drawerContent"),resultsBox=document.getElementById("searchResults"),input=document.getElementById("movieSearch"),errorBox=document.getElementById("startupError");
const ns="http://www.w3.org/2000/svg",nodeMap=new Map(),edgeMap=new Map();
let panX=0,panY=0,scale=.88,dragging=false,dragStart=null,pointerId=null,timer,focusedId=null;
const keyFor=(type,id)=>`${type}:${id}`;
const COLORS={movie:"#d89cff",director:"#45d0d5",person:"#45d0d5",actor:"#ef5c91",genre:"#f4a340",movement:"#b35df2",style:"#7c83ff",country:"#83d66d",decade:"#f0c85a",company:"#61a9f7"};
const REGION_POS={genre:{x:-650,y:-150},movement:{x:-230,y:210},country:{x:610,y:-160},decade:{x:650,y:300},style:{x:-250,y:420},company:{x:360,y:420},director:{x:0,y:-270}};
const SEEDS={
 genre:[{id:878,name:"Science Fiction"},{id:80,name:"Crime"},{id:27,name:"Horror"},{id:18,name:"Drama"},{id:16,name:"Animation"},{id:37,name:"Western"},{id:35,name:"Comedy"},{id:53,name:"Thriller"}],
 movement:["French New Wave","Italian Neorealism","German Expressionism","New Hollywood","Dogme 95","Slow Cinema","Korean New Wave","Hong Kong New Wave"].map(name=>({id:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),name})),
 country:[{id:"JP",name:"Japan"},{id:"FR",name:"France"},{id:"KR",name:"South Korea"},{id:"IN",name:"India"},{id:"IR",name:"Iran"},{id:"HK",name:"Hong Kong"},{id:"IT",name:"Italy"},{id:"US",name:"United States"}],
 decade:[1950,1960,1970,1980,1990,2000,2010,2020].map(id=>({id:String(id),name:`${id}s`})),
 style:[{id:9715,name:"revenge"},{id:4565,name:"dystopia"},{id:10183,name:"independent film"},{id:10349,name:"surrealism"},{id:180547,name:"coming of age"},{id:9823,name:"neo-noir"}],company:[]
};
function setTransform(){viewport.setAttribute("transform",`translate(${panX} ${panY}) scale(${scale})`)}
function showError(e){console.error(e);errorBox.textContent=e?.message||"CineMap could not load";errorBox.style.display="block";setTimeout(()=>errorBox.style.display="none",4200)}
async function getJson(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw new Error(d.details||d.error||"Request failed");return d}
function updateStats(){stats.textContent=`${nodeMap.size} places · ${edgeMap.size} connections`}
function typeMeta(type,data){if(type==="movie")return data.release_date?.slice(0,4)||"FILM";if(type==="director")return"DIRECTOR";if(type==="actor")return"PERFORMER";if(type==="person")return(data.known_for_department||data.job||"FILMMAKER").toUpperCase();if(type==="genre")return"GENRE";if(type==="movement")return"MOVEMENT";if(type==="country")return"WORLD CINEMA";if(type==="decade")return"ERA";if(type==="style")return"THEME / STYLE";if(type==="company")return"STUDIO";return"CINEMA"}
function addRegion(type,title,subtitle){if(document.getElementById(`region-${type}`))return;const p=REGION_POS[type];if(!p)return;const g=document.createElementNS(ns,"g");g.id=`region-${type}`;const color=COLORS[type]||"#8894aa";const halo=document.createElementNS(ns,"path");halo.setAttribute("class","region-halo");halo.setAttribute("stroke",color);halo.setAttribute("d",`M ${p.x-105} ${p.y-92} C ${p.x-145} ${p.y-25}, ${p.x-135} ${p.y+85}, ${p.x-72} ${p.y+118} C ${p.x-15} ${p.y+148}, ${p.x+100} ${p.y+128}, ${p.x+120} ${p.y+45} C ${p.x+140} ${p.y-35}, ${p.x+95} ${p.y-100}, ${p.x+20} ${p.y-108}`);const t=document.createElementNS(ns,"text");t.setAttribute("class","region-label");t.setAttribute("x",p.x);t.setAttribute("y",p.y-105);t.setAttribute("fill",color);t.setAttribute("text-anchor","middle");t.textContent=title;const s=document.createElementNS(ns,"text");s.setAttribute("class","region-sub");s.setAttribute("x",p.x);s.setAttribute("y",p.y-88);s.setAttribute("text-anchor","middle");s.textContent=subtitle;g.append(halo,t,s);regionsLayer.appendChild(g)}
function regionPosition(type,index,total,parent){if(parent){const p=nodeMap.get(parent);if(p){const ring=150+Math.floor(index/8)*95;const angle=(-Math.PI*.85)+(index%8)*(Math.PI*1.7/Math.max(7,Math.min(7,total-1)));return{x:p.x+Math.cos(angle)*ring,y:p.y+Math.sin(angle)*ring}}}const base=REGION_POS[type]||{x:0,y:0};const cols=type==="decade"?2:1;const row=Math.floor(index/cols),col=index%cols;return{x:base.x+(col-(cols-1)/2)*78,y:base.y-60+row*25}}
function addNode(type,data,parent=null,index=0,total=1,seed=false){const id=keyFor(type,data.id);if(nodeMap.has(id))return id;const pos=regionPosition(type,index,total,parent);const node={id,type,data,x:pos.x,y:pos.y,parent,seed};nodeMap.set(id,node);renderNode(node);updateStats();return id}
function renderNode(node){const g=document.createElementNS(ns,"g");g.setAttribute("class",`node ${node.type}${node.seed?" seed":""}`);g.setAttribute("transform",`translate(${node.x} ${node.y})`);g.dataset.nodeId=node.id;const title=document.createElementNS(ns,"text");title.setAttribute("class","node-title");title.setAttribute("x","0");title.setAttribute("y","0");title.setAttribute("text-anchor","middle");title.setAttribute("fill",COLORS[node.type]||"#d8deea");const label=node.data.title||node.data.name||"Untitled";title.textContent=label.length>30?`${label.slice(0,29)}…`:label;const meta=document.createElementNS(ns,"text");meta.setAttribute("class","node-meta");meta.setAttribute("x","0");meta.setAttribute("y","12");meta.setAttribute("text-anchor","middle");meta.textContent=node.seed?"":typeMeta(node.type,node.data);g.append(title,meta);g.addEventListener("click",e=>{e.stopPropagation();focusNode(node.id);expandNode(node).catch(showError)});nodesLayer.appendChild(g)}
function addEdge(from,to,label=""){const id=`${from}|${to}|${label}`;if(edgeMap.has(id))return;const a=nodeMap.get(from),b=nodeMap.get(to);if(!a||!b)return;edgeMap.set(id,{id,from,to,label});const g=document.createElementNS(ns,"g");g.dataset.edgeId=id;const path=document.createElementNS(ns,"path");path.setAttribute("class","edge");path.setAttribute("stroke",COLORS[b.type]||"#8290a6");path.setAttribute("d",curvePath(a,b));g.appendChild(path);if(label){const t=document.createElementNS(ns,"text");t.setAttribute("class","edge-label");t.setAttribute("x",(a.x+b.x)/2);t.setAttribute("y",(a.y+b.y)/2-5);t.setAttribute("text-anchor","middle");t.textContent=label;g.appendChild(t)}edgesLayer.appendChild(g);updateStats()}
function curvePath(a,b){const dx=b.x-a.x,dy=b.y-a.y,mx=(a.x+b.x)/2,my=(a.y+b.y)/2;const bend=Math.min(80,Math.max(25,Math.abs(dx+dy)*.06));const nx=-dy/(Math.hypot(dx,dy)||1),ny=dx/(Math.hypot(dx,dy)||1);return`M ${a.x} ${a.y} Q ${mx+nx*bend} ${my+ny*bend} ${b.x} ${b.y}`}
function seedAtlas(){regionsLayer.innerHTML="";edgesLayer.innerHTML="";nodesLayer.innerHTML="";nodeMap.clear();edgeMap.clear();focusedId=null;addRegion("genre","GENRES","STORY FORMS");addRegion("movement","CINEMATIC MOVEMENTS","WAVES & REVOLUTIONS");addRegion("country","WORLD CINEMA","NATIONAL TRADITIONS");addRegion("decade","DECADES","CINEMA THROUGH TIME");addRegion("style","THEMES & STYLES","VISUAL & NARRATIVE DNA");Object.entries(SEEDS).forEach(([type,items])=>items.forEach((item,i)=>addNode(type,item,null,i,items.length,true)));updateStats();clearFocus();fitMap(.78)}
function focusNode(id){focusedId=id;const connected=new Set([id]);edgeMap.forEach(e=>{if(e.from===id){connected.add(e.to)}if(e.to===id){connected.add(e.from)}});nodesLayer.querySelectorAll(".node").forEach(el=>{const nid=el.dataset.nodeId;el.classList.toggle("focused",nid===id);el.classList.toggle("dimmed",!connected.has(nid))});edgesLayer.querySelectorAll("g[data-edge-id]").forEach(g=>{const e=edgeMap.get(g.dataset.edgeId);const active=e&&(e.from===id||e.to===id);const path=g.querySelector(".edge");path?.classList.toggle("active",active);path?.classList.toggle("dimmed",!active)});regionsLayer.style.opacity=".24"}
function clearFocus(){nodesLayer.querySelectorAll(".node").forEach(el=>el.classList.remove("focused","dimmed"));edgesLayer.querySelectorAll(".edge").forEach(el=>el.classList.remove("active","dimmed"));regionsLayer.style.opacity="1"}
function centerOn(id,zoom=.96){const n=nodeMap.get(id);if(!n)return;const r=svg.getBoundingClientRect();scale=zoom;panX=r.width/2-n.x*scale+70;panY=r.height/2-n.y*scale;setTransform()}
function fitMap(max=.9){if(!nodeMap.size)return;const vals=[...nodeMap.values()],xs=vals.map(n=>n.x),ys=vals.map(n=>n.y),minX=Math.min(...xs)-190,maxX=Math.max(...xs)+190,minY=Math.min(...ys)-160,maxY=Math.max(...ys)+160,r=svg.getBoundingClientRect();scale=Math.min(max,r.width/(maxX-minX),r.height/(maxY-minY));panX=r.width/2-((minX+maxX)/2)*scale+40;panY=r.height/2-((minY+maxY)/2)*scale;setTransform()}
async function expandNode(node){if(node.type==="movie")return loadMovie(node.data.id,true);if(["director","actor","person"].includes(node.type))return loadPerson(node.data.id,true);return loadCollection(node.type,node.data,true)}
async function loadMovie(id,focus=true){const data=await getJson(`${API}?id=${encodeURIComponent(id)}`);const root=addNode("movie",data.movie);const children=[];if(data.director)children.push({type:"director",data:data.director,label:"directed by"});(data.crew||[]).slice(0,3).forEach(p=>children.push({type:"person",data:p,label:(p.job||"crew").toLowerCase()}));(data.cast||[]).slice(0,3).forEach(p=>children.push({type:"actor",data:p,label:"cast"}));(data.genres||[]).slice(0,3).forEach(x=>children.push({type:"genre",data:x,label:"genre"}));(data.styles||[]).slice(0,3).forEach(x=>children.push({type:"style",data:x,label:"theme/style"}));(data.companies||[]).slice(0,2).forEach(x=>children.push({type:"company",data:x,label:"studio"}));(data.countries||[]).slice(0,2).forEach(x=>children.push({type:"country",data:{id:x.iso_3166_1,name:x.name},label:"country"}));(data.related||[]).slice(0,7).forEach(x=>children.push({type:"movie",data:x,label:"cinematic kinship"}));children.forEach((c,i)=>addEdge(root,addNode(c.type,c.data,root,i,children.length),c.label));showMovieDetails(data);focusNode(root);if(focus)centerOn(root,.92)}
async function loadPerson(id,focus=true){const data=await getJson(`${API}?personId=${encodeURIComponent(id)}`);const type=data.type||"person",root=addNode(type,data.person);(data.movies||[]).slice(0,13).forEach((m,i)=>addEdge(root,addNode("movie",m,root,i,13),data.department||"filmography"));showCollectionDetails(data.department||"Filmmaker",data.person.name,data.person.biography,data.movies,data.person.profile_path);focusNode(root);if(focus)centerOn(root,.9)}
async function loadCollection(type,item,focus=true){let url;if(type==="genre")url=`${API}?genreId=${item.id}`;if(type==="style")url=`${API}?keywordId=${item.id}`;if(type==="movement")url=`${API}?movement=${encodeURIComponent(item.name)}`;if(type==="country")url=`${API}?country=${encodeURIComponent(item.id)}`;if(type==="decade")url=`${API}?decade=${encodeURIComponent(item.id)}`;if(type==="company")url=`${API}?companyId=${encodeURIComponent(item.id)}`;if(!url)return;const data=await getJson(url);const entity=data.genre||data.style||data.movement||data.country||data.decade||data.company||item,root=addNode(type,entity);(data.movies||[]).slice(0,14).forEach((m,i)=>addEdge(root,addNode("movie",m,root,i,14),"belongs here"));showCollectionDetails(typeMeta(type,entity),entity.name,collectionBlurb(type,entity.name),data.movies,entity.logo_path||null);focusNode(root);if(focus)centerOn(root,.88)}
function collectionBlurb(type,name){return({genre:`Explore defining and popular films within ${name}.`,movement:`Trace films associated with the ${name} tradition and its cinematic vocabulary.`,country:`Explore influential films from ${name}.`,decade:`Move through major films that shaped the ${name}.`,style:`Follow the stylistic or thematic thread “${name}” across cinema.`,company:`Explore films associated with ${name}.`})[type]||"Explore this branch of cinema."}
function chip(type,id,label){return `<button data-type="${type}" data-id="${id}">${label}</button>`}
function showMovieDetails(data){const m=data.movie;drawerContent.innerHTML=`<div class="detail-head"><img class="poster" src="${m.poster_path?IMG+m.poster_path:"mmlogo.png"}" alt=""><div><div class="meta">FILM</div><h2>${m.title}</h2><div class="meta">${[m.release_date?.slice(0,4),m.runtime?`${m.runtime} min`:"",m.vote_average?`${m.vote_average.toFixed(1)}/10`:""].filter(Boolean).join(" · ")}</div>${data.director?`<div class="meta" style="margin-top:6px">Directed by ${data.director.name}</div>`:""}</div></div><p class="overview">${m.overview||"No overview available."}</p><h3>Follow a thread</h3><div class="chips">${(data.genres||[]).map(x=>chip("genre",x.id,x.name)).join("")}${(data.styles||[]).map(x=>chip("style",x.id,x.name)).join("")}${data.director?chip("person",data.director.id,data.director.name):""}${(data.cast||[]).slice(0,4).map(x=>chip("person",x.id,x.name)).join("")}${(data.crew||[]).slice(0,4).map(x=>chip("person",x.id,`${x.name} · ${x.job}`)).join("")}</div><h3>Cinematic kinship</h3><div class="chips">${(data.related||[]).slice(0,10).map(x=>chip("movie",x.id,x.title)).join("")}</div>`;wireDrawer();drawer.classList.add("open")}
function showCollectionDetails(kind,title,desc,movies,image){drawerContent.innerHTML=`<div class="detail-head">${image?`<img class="poster" src="${IMG+image}" alt="">`:""}<div><div class="meta">${kind}</div><h2>${title}</h2><div class="meta">${movies?.length||0} films on this branch</div></div></div><p class="overview">${desc||"Explore this branch of cinema."}</p><h3>Continue exploring</h3><div class="chips">${(movies||[]).slice(0,18).map(x=>chip("movie",x.id,x.title)).join("")}</div>`;wireDrawer();drawer.classList.add("open")}
function wireDrawer(){drawerContent.querySelectorAll("button[data-type]").forEach(b=>b.onclick=()=>{const type=b.dataset.type,id=b.dataset.id;if(type==="movie")loadMovie(Number(id),true).catch(showError);else if(type==="person")loadPerson(Number(id),true).catch(showError);else{const n=nodeMap.get(keyFor(type,id));if(n)expandNode(n).catch(showError)}})}
function icon(type){return({movie:"🎬",person:"👤",genre:"G",style:"S",movement:"M",country:"🌍",decade:"◷",company:"◆"})[type]||"•"}
function imageFor(item){return item.image?`${IMG}${item.image}`:""}
function openSearchResult(item){resultsBox.style.display="none";input.value=item.name;if(item.type==="movie")return loadMovie(item.id,true).catch(showError);if(item.type==="person")return loadPerson(item.id,true).catch(showError);return loadCollection(item.type,item,true).catch(showError)}
input.addEventListener("input",()=>{clearTimeout(timer);const q=input.value.trim();if(q.length<2){resultsBox.style.display="none";return}timer=setTimeout(async()=>{try{const results=await getJson(`${API}?query=${encodeURIComponent(q)}`);resultsBox.innerHTML=results.map((item,i)=>`<div class="result" data-index="${i}">${item.image?`<img src="${imageFor(item)}" alt="">`:`<div class="result-icon">${icon(item.type)}</div>`}<div><strong>${item.name}</strong><span>${item.subtitle||item.type}</span></div></div>`).join("");resultsBox.style.display=results.length?"block":"none";resultsBox.querySelectorAll(".result").forEach(r=>r.onclick=()=>openSearchResult(results[Number(r.dataset.index)]))}catch(e){showError(e)}},240)});
document.querySelectorAll("[data-atlas]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-atlas]").forEach(x=>x.classList.remove("active"));b.classList.add("active");const type=b.dataset.atlas;if(type==="influence"){clearFocus();fitMap(.78);return}if(type==="director"||type==="company"){input.focus();input.value="";input.placeholder=type==="director"?"Search a director, cinematographer, composer, writer…":"Search a studio or production company…";return}const p=REGION_POS[type];if(p){const r=svg.getBoundingClientRect();scale=1.05;panX=r.width/2-p.x*scale;panY=r.height/2-p.y*scale;setTransform()}});
document.getElementById("closeDrawer").onclick=()=>drawer.classList.remove("open");document.getElementById("resetButton").onclick=()=>{drawer.classList.remove("open");input.value="";input.placeholder="Search anything in cinema…";seedAtlas()};document.getElementById("randomButton").onclick=async()=>{try{const m=await getJson(`${API}?random=1&t=${Date.now()}`);if(m)loadMovie(m.id,true)}catch(e){showError(e)}};
svg.addEventListener("click",e=>{if(e.target===svg||e.target.closest?.("#regionsLayer")){clearFocus();drawer.classList.remove("open")}});svg.addEventListener("wheel",e=>{e.preventDefault();const r=svg.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,old=scale;scale=Math.min(2.15,Math.max(.3,scale*(e.deltaY<0?1.1:.91)));panX=mx-((mx-panX)/old)*scale;panY=my-((my-panY)/old)*scale;setTransform()},{passive:false});svg.addEventListener("pointerdown",e=>{if(e.target.closest?.(".node"))return;dragging=true;pointerId=e.pointerId;dragStart={x:e.clientX-panX,y:e.clientY-panY};svg.setPointerCapture(e.pointerId);svg.style.cursor="grabbing"});svg.addEventListener("pointermove",e=>{if(!dragging||e.pointerId!==pointerId)return;panX=e.clientX-dragStart.x;panY=e.clientY-dragStart.y;setTransform()});function endDrag(e){if(!dragging||e.pointerId!==pointerId)return;dragging=false;if(svg.hasPointerCapture(pointerId))svg.releasePointerCapture(pointerId);pointerId=null;svg.style.cursor="grab"}svg.addEventListener("pointerup",endDrag);svg.addEventListener("pointercancel",endDrag);window.addEventListener("resize",()=>fitMap(.78));seedAtlas();