const API="https://moodmatch-api-ko99.vercel.app/api/cinemap";
const IMG="https://image.tmdb.org/t/p/w500";
const svg=document.getElementById("graph"),viewport=document.getElementById("viewport"),regionsLayer=document.getElementById("regionsLayer"),edgesLayer=document.getElementById("edgesLayer"),nodesLayer=document.getElementById("nodesLayer"),stats=document.getElementById("mapStats"),drawer=document.getElementById("drawer"),drawerContent=document.getElementById("drawerContent"),resultsBox=document.getElementById("searchResults"),input=document.getElementById("movieSearch"),errorBox=document.getElementById("startupError");
const ns="http://www.w3.org/2000/svg",nodeMap=new Map(),edgeMap=new Map();let panX=0,panY=0,scale=.92,dragging=false,dragStart=null,pointerId=null,timer;
const keyFor=(type,id)=>`${type}:${id}`;
const REGION_POS={genre:{x:-620,y:-160},movement:{x:0,y:-270},country:{x:610,y:-130},decade:{x:-480,y:360},style:{x:140,y:370},company:{x:660,y:360},director:{x:0,y:70}};
const SEEDS={
 genre:[{id:878,name:"Science Fiction"},{id:80,name:"Crime"},{id:27,name:"Horror"},{id:18,name:"Drama"},{id:16,name:"Animation"},{id:37,name:"Western"}],
 movement:["French New Wave","Italian Neorealism","German Expressionism","New Hollywood","Dogme 95","Slow Cinema"].map(name=>({id:name.toLowerCase().replace(/[^a-z0-9]+/g,"-"),name})),
 country:[{id:"JP",name:"Japan"},{id:"FR",name:"France"},{id:"KR",name:"South Korea"},{id:"IN",name:"India"},{id:"IR",name:"Iran"},{id:"HK",name:"Hong Kong"}],
 decade:[1950,1960,1970,1980,1990,2000,2010,2020].map(id=>({id:String(id),name:`${id}s`})),
 style:[{id:9715,name:"revenge"},{id:4565,name:"dystopia"},{id:10183,name:"independent film"},{id:10349,name:"surrealism"},{id:180547,name:"coming of age"}],
 company:[]
};
function setTransform(){viewport.setAttribute("transform",`translate(${panX} ${panY}) scale(${scale})`)}
function showError(e){console.error(e);errorBox.textContent=e?.message||"CineMap could not load";errorBox.style.display="block";setTimeout(()=>errorBox.style.display="none",4500)}
async function getJson(url){const r=await fetch(url);const d=await r.json();if(!r.ok)throw new Error(d.details||d.error||"Request failed");return d}
function updateStats(){stats.textContent=`${nodeMap.size} places · ${edgeMap.size} connections`}
function nodeDims(node){const label=node.data.title||node.data.name||"Untitled";const w=Math.max(112,Math.min(196,72+label.length*5.3));return{w,h:node.type==="movie"?50:44}}
function typeMeta(type,data){if(type==="movie")return data.release_date?.slice(0,4)||"FILM";if(type==="director")return"DIRECTOR";if(type==="actor")return"PERFORMER";if(type==="person")return(data.known_for_department||"FILMMAKER").toUpperCase();if(type==="genre")return"GENRE";if(type==="movement")return"MOVEMENT";if(type==="country")return"WORLD CINEMA";if(type==="decade")return"ERA";if(type==="style")return"THEME / STYLE";if(type==="company")return"STUDIO";return"CINEMA"}
function addRegion(type,title,subtitle){if(document.getElementById(`region-${type}`))return;const pos=REGION_POS[type]||{x:0,y:0};const g=document.createElementNS(ns,"g");g.id=`region-${type}`;const t=document.createElementNS(ns,"text");t.setAttribute("class","region-label");t.setAttribute("x",pos.x);t.setAttribute("y",pos.y-115);t.setAttribute("text-anchor","middle");t.textContent=title;const s=document.createElementNS(ns,"text");s.setAttribute("class","region-sub");s.setAttribute("x",pos.x);s.setAttribute("y",pos.y-94);s.setAttribute("text-anchor","middle");s.textContent=subtitle;g.append(t,s);regionsLayer.appendChild(g)}
function regionPosition(type,index,total,parent){if(parent){const p=nodeMap.get(parent);if(p){const cols=Math.ceil(Math.sqrt(total));const col=index%cols,row=Math.floor(index/cols);return{x:p.x+(col-(cols-1)/2)*190,y:p.y+115+row*88}}}const base=REGION_POS[type]||{x:0,y:0};const cols=type==="decade"?4:3,col=index%cols,row=Math.floor(index/cols);return{x:base.x+(col-(cols-1)/2)*175,y:base.y+row*82}}
function addNode(type,data,parent=null,index=0,total=1){const id=keyFor(type,data.id);if(nodeMap.has(id))return id;const pos=regionPosition(type,index,total,parent);const node={id,type,data,x:pos.x,y:pos.y};nodeMap.set(id,node);renderNode(node);updateStats();return id}
function renderNode(node){const d=nodeDims(node),g=document.createElementNS(ns,"g");g.setAttribute("class",`node ${node.type}`);g.setAttribute("transform",`translate(${node.x} ${node.y})`);g.dataset.nodeId=node.id;const rect=document.createElementNS(ns,"rect");rect.setAttribute("class","node-bg");rect.setAttribute("x",-d.w/2);rect.setAttribute("y",-d.h/2);rect.setAttribute("width",d.w);rect.setAttribute("height",d.h);rect.setAttribute("rx","11");const title=document.createElementNS(ns,"text");title.setAttribute("class","node-title");title.setAttribute("x","0");title.setAttribute("y","-2");title.setAttribute("text-anchor","middle");const label=node.data.title||node.data.name||"Untitled";title.textContent=label.length>28?`${label.slice(0,27)}…`:label;const meta=document.createElementNS(ns,"text");meta.setAttribute("class","node-meta");meta.setAttribute("x","0");meta.setAttribute("y","14");meta.setAttribute("text-anchor","middle");meta.textContent=typeMeta(node.type,node.data);g.append(rect,title,meta);g.addEventListener("click",e=>{e.stopPropagation();expandNode(node).catch(showError)});nodesLayer.appendChild(g)}
function addEdge(from,to,label=""){const id=`${from}|${to}|${label}`;if(edgeMap.has(id))return;edgeMap.set(id,{from,to,label});const a=nodeMap.get(from),b=nodeMap.get(to);if(!a||!b)return;const g=document.createElementNS(ns,"g");const line=document.createElementNS(ns,"line");line.setAttribute("class",`edge ${label.includes("lineage")?"influence":""}`);line.setAttribute("x1",a.x);line.setAttribute("y1",a.y+24);line.setAttribute("x2",b.x);line.setAttribute("y2",b.y-24);g.appendChild(line);if(label){const t=document.createElementNS(ns,"text");t.setAttribute("class","edge-label");t.setAttribute("x",(a.x+b.x)/2);t.setAttribute("y",(a.y+b.y)/2-4);t.setAttribute("text-anchor","middle");t.textContent=label;g.appendChild(t)}edgesLayer.appendChild(g);updateStats()}
function seedAtlas(){regionsLayer.innerHTML="";edgesLayer.innerHTML="";nodesLayer.innerHTML="";nodeMap.clear();edgeMap.clear();addRegion("genre","GENRES","STORY FORMS & TRADITIONS");addRegion("movement","MOVEMENTS","SCHOOLS, WAVES & REVOLUTIONS");addRegion("country","WORLD CINEMA","NATIONAL & REGIONAL TRADITIONS");addRegion("decade","ERAS","CINEMA THROUGH TIME");addRegion("style","THEMES & STYLES","VISUAL & NARRATIVE DNA");Object.entries(SEEDS).forEach(([type,items])=>items.forEach((item,i)=>addNode(type,item,null,i,items.length)));updateStats();fitMap(.82)}
function centerOn(id,zoom=1.05){const n=nodeMap.get(id);if(!n)return;const r=svg.getBoundingClientRect();scale=zoom;panX=r.width/2-n.x*scale;panY=r.height/2-n.y*scale;setTransform()}
function fitMap(max=.94){if(!nodeMap.size)return;const vals=[...nodeMap.values()],xs=vals.map(n=>n.x),ys=vals.map(n=>n.y),minX=Math.min(...xs)-170,maxX=Math.max(...xs)+170,minY=Math.min(...ys)-145,maxY=Math.max(...ys)+145,r=svg.getBoundingClientRect();scale=Math.min(max,r.width/(maxX-minX),r.height/(maxY-minY));panX=r.width/2-((minX+maxX)/2)*scale;panY=r.height/2-((minY+maxY)/2)*scale;setTransform()}
async function expandNode(node){if(node.type==="movie")return loadMovie(node.data.id,true);if(["director","actor","person"].includes(node.type))return loadPerson(node.data.id,true);if(node.type==="genre")return loadCollection("genre",node.data,true);if(node.type==="style")return loadCollection("style",node.data,true);if(node.type==="movement")return loadCollection("movement",node.data,true);if(node.type==="country")return loadCollection("country",node.data,true);if(node.type==="decade")return loadCollection("decade",node.data,true);if(node.type==="company")return loadCollection("company",node.data,true)}
async function loadMovie(id,focus=true){const data=await getJson(`${API}?id=${encodeURIComponent(id)}`);const root=addNode("movie",data.movie);const children=[];if(data.director)children.push({type:"director",data:data.director,label:"directed by"});(data.crew||[]).slice(0,4).forEach(p=>children.push({type:"person",data:p,label:p.job?.toLowerCase()||"crew"}));(data.cast||[]).slice(0,3).forEach(p=>children.push({type:"actor",data:p,label:"performed by"}));(data.genres||[]).slice(0,3).forEach(x=>children.push({type:"genre",data:x,label:"genre"}));(data.styles||[]).slice(0,3).forEach(x=>children.push({type:"style",data:x,label:"style"}));(data.companies||[]).slice(0,2).forEach(x=>children.push({type:"company",data:x,label:"studio"}));(data.countries||[]).slice(0,2).forEach(x=>children.push({type:"country",data:{id:x.iso_3166_1,name:x.name},label:"country"}));(data.related||[]).slice(0,8).forEach(x=>children.push({type:"movie",data:x,label:"cinematic lineage"}));children.forEach((c,i)=>addEdge(root,addNode(c.type,c.data,root,i,children.length),c.label));showMovieDetails(data);if(focus)centerOn(root,.88)}
async function loadPerson(id,focus=true){const data=await getJson(`${API}?personId=${encodeURIComponent(id)}`);const type=data.type||"person",root=addNode(type,data.person);(data.movies||[]).slice(0,15).forEach((m,i)=>addEdge(root,addNode("movie",m,root,i,15),data.department||"filmography"));showCollectionDetails(data.department||"Filmmaker",data.person.name,data.person.biography,data.movies,data.person.profile_path);if(focus)centerOn(root,.88)}
async function loadCollection(type,item,focus=true){let url;if(type==="genre")url=`${API}?genreId=${item.id}`;if(type==="style")url=`${API}?keywordId=${item.id}`;if(type==="movement")url=`${API}?movement=${encodeURIComponent(item.name)}`;if(type==="country")url=`${API}?country=${encodeURIComponent(item.id)}`;if(type==="decade")url=`${API}?decade=${encodeURIComponent(item.id)}`;if(type==="company")url=`${API}?companyId=${encodeURIComponent(item.id)}`;const data=await getJson(url);const entity=data.genre||data.style||data.movement||data.country||data.decade||data.company||item,root=addNode(type,entity);(data.movies||[]).slice(0,18).forEach((m,i)=>addEdge(root,addNode("movie",m,root,i,18),"belongs here"));showCollectionDetails(typeMeta(type,entity),entity.name,collectionBlurb(type,entity.name),data.movies,entity.logo_path||null);if(focus)centerOn(root,.82)}
function collectionBlurb(type,name){return({genre:`Explore defining and popular films within ${name}.`,movement:`Trace films associated with the ${name} tradition and its cinematic vocabulary.`,country:`Explore influential and widely seen films from ${name}.`,decade:`Move through major films that shaped the ${name}.`,style:`Follow the theme or stylistic thread “${name}” across different filmmakers and eras.`,company:`Explore films associated with ${name}.`})[type]||"Explore this branch of cinema."}
function showMovieDetails(data){const m=data.movie;drawerContent.innerHTML=`<div class="detail-head"><img class="poster" src="${m.poster_path?IMG+m.poster_path:"mmlogo.png"}"><div><div class="meta">FILM</div><h2>${m.title}</h2><div class="meta">${[m.release_date?.slice(0,4),m.runtime?`${m.runtime} min`:"",m.vote_average?`${m.vote_average.toFixed(1)}/10`:""].filter(Boolean).join(" · ")}</div>${data.director?`<div class="meta" style="margin-top:6px">${data.director.name}</div>`:""}</div></div><p class="overview">${m.overview||"No overview available."}</p><h3>Follow a thread</h3><div class="chips">${(data.genres||[]).map(x=>chip("genre",x.id,x.name)).join("")}${(data.styles||[]).map(x=>chip("style",x.id,x.name)).join("")}${data.director?chip("person",data.director.id,data.director.name):""}${(data.cast||[]).slice(0,4).map(x=>chip("person",x.id,x.name)).join("")}${(data.crew||[]).slice(0,4).map(x=>chip("person",x.id,`${x.name} · ${x.job}`)).join("")}</div><h3>Cinematic kinship</h3><div class="chips">${(data.related||[]).slice(0,10).map(x=>chip("movie",x.id,x.title)).join("")}</div>`;wireDrawer();drawer.classList.add("open")}
function showCollectionDetails(kind,title,desc,movies,image){drawerContent.innerHTML=`<div class="detail-head">${image?`<img class="poster" src="${IMG+image}">`:""}<div><div class="meta">${kind}</div><h2>${title}</h2><div class="meta">${movies?.length||0} films on this branch</div></div></div><p class="overview">${desc||"Explore this branch of cinema."}</p><h3>Continue exploring</h3><div class="chips">${(movies||[]).slice(0,18).map(x=>chip("movie",x.id,x.title)).join("")}</div>`;wireDrawer();drawer.classList.add("open")}
function chip(type,id,label){return `<button data-type="${type}" data-id="${id}">${label}</button>`}
function wireDrawer(){drawerContent.querySelectorAll("button[data-type]").forEach(b=>b.onclick=()=>{const type=b.dataset.type,id=b.dataset.id;if(type==="movie")loadMovie(Number(id),true).catch(showError);else if(type==="person")loadPerson(Number(id),true).catch(showError);else{const n=nodeMap.get(keyFor(type,id));if(n)expandNode(n).catch(showError)}})}
function icon(type){return({movie:"🎬",person:"👤",genre:"G",style:"S",movement:"M",country:"🌍",decade:"◷",company:"◆"})[type]||"•"}
function imageFor(item){return item.image?`${IMG}${item.image}`:""}
function openSearchResult(item){resultsBox.style.display="none";input.value=item.name;if(item.type==="movie")return loadMovie(item.id,true).catch(showError);if(item.type==="person")return loadPerson(item.id,true).catch(showError);return loadCollection(item.type,item,true).catch(showError)}
input.addEventListener("input",()=>{clearTimeout(timer);const q=input.value.trim();if(q.length<2){resultsBox.style.display="none";return}timer=setTimeout(async()=>{try{const results=await getJson(`${API}?query=${encodeURIComponent(q)}`);resultsBox.innerHTML=results.map((item,i)=>`<div class="result" data-index="${i}">${item.image?`<img src="${imageFor(item)}">`:`<div class="result-icon">${icon(item.type)}</div>`}<div><strong>${item.name}</strong><span>${item.subtitle||item.type}</span></div></div>`).join("");resultsBox.style.display=results.length?"block":"none";resultsBox.querySelectorAll(".result").forEach(r=>r.onclick=()=>openSearchResult(results[Number(r.dataset.index)]))}catch(e){showError(e)}},240)});
document.querySelectorAll("[data-atlas]").forEach(b=>b.onclick=()=>{const type=b.dataset.atlas;if(type==="director"){input.focus();input.value="";input.placeholder="Search a director, cinematographer, composer, writer…";return}if(type==="company"){input.focus();input.value="";input.placeholder="Search a studio or production company…";return}const pos=REGION_POS[type];if(pos){const r=svg.getBoundingClientRect();scale=1.05;panX=r.width/2-pos.x*scale;panY=r.height/2-pos.y*scale;setTransform()}});
document.getElementById("closeDrawer").onclick=()=>drawer.classList.remove("open");document.getElementById("resetButton").onclick=()=>{drawer.classList.remove("open");input.value="";seedAtlas()};document.getElementById("randomButton").onclick=async()=>{try{const m=await getJson(`${API}?random=1&t=${Date.now()}`);if(m)loadMovie(m.id,true)}catch(e){showError(e)}};
svg.addEventListener("wheel",e=>{e.preventDefault();const r=svg.getBoundingClientRect(),mx=e.clientX-r.left,my=e.clientY-r.top,old=scale;scale=Math.min(2.2,Math.max(.28,scale*(e.deltaY<0?1.11:.9)));panX=mx-((mx-panX)/old)*scale;panY=my-((my-panY)/old)*scale;setTransform()},{passive:false});svg.addEventListener("pointerdown",e=>{if(e.target.closest?.(".node"))return;dragging=true;pointerId=e.pointerId;dragStart={x:e.clientX-panX,y:e.clientY-panY};svg.setPointerCapture(e.pointerId);svg.style.cursor="grabbing"});svg.addEventListener("pointermove",e=>{if(!dragging||e.pointerId!==pointerId)return;panX=e.clientX-dragStart.x;panY=e.clientY-dragStart.y;setTransform()});function endDrag(e){if(!dragging||e.pointerId!==pointerId)return;dragging=false;if(svg.hasPointerCapture(pointerId))svg.releasePointerCapture(pointerId);pointerId=null;svg.style.cursor="grab"}svg.addEventListener("pointerup",endDrag);svg.addEventListener("pointercancel",endDrag);window.addEventListener("resize",()=>fitMap(.82));seedAtlas();