const API = "https://moodmatch-api-ko99.vercel.app/api/cinemap";
const IMG = "https://image.tmdb.org/t/p/w500";
const svg = document.getElementById("graph");
const viewport = document.getElementById("viewport");
const edgesLayer = document.getElementById("edgesLayer");
const nodesLayer = document.getElementById("nodesLayer");
const stats = document.getElementById("mapStats");
const drawer = document.getElementById("drawer");
const drawerContent = document.getElementById("drawerContent");
const resultsBox = document.getElementById("searchResults");
const input = document.getElementById("movieSearch");
const errorBox = document.getElementById("startupError");
const nodeMap = new Map();
const edgeMap = new Map();
let panX = 0, panY = 0, scale = 1, dragging = false, dragStart = null, activePointerId = null, timer;
const ns = "http://www.w3.org/2000/svg";
const keyFor = (type, id) => `${type}:${id}`;

function setTransform(){viewport.setAttribute("transform",`translate(${panX} ${panY}) scale(${scale})`)}
function updateStats(){stats.textContent=`${nodeMap.size} nodes · ${edgeMap.size} connections`}
function showError(error){console.error(error);errorBox.textContent=error?.message||"CineMap could not load.";errorBox.style.display="block"}
async function getJson(url){const response=await fetch(url);const data=await response.json();if(!response.ok)throw new Error(data.details||data.error||"Request failed");return data}
function positionFor(type,parentId,index,total){const parent=parentId?nodeMap.get(parentId):null;const cx=parent?.x??0,cy=parent?.y??0;const radius=type==="movie"?235:165;const angle=total>1?(Math.PI*2*index)/total-Math.PI/2:0;return{x:cx+Math.cos(angle)*radius,y:cy+Math.sin(angle)*radius}}
function addNode(type,data,parentId=null,index=0,total=1){const id=keyFor(type,data.id);if(nodeMap.has(id))return id;const pos=nodeMap.size?positionFor(type,parentId,index,total):{x:0,y:0};nodeMap.set(id,{id,type,data,x:pos.x,y:pos.y});renderNode(nodeMap.get(id));updateStats();return id}
function addEdge(from,to,label){const id=`${from}|${to}|${label}`;if(edgeMap.has(id))return;edgeMap.set(id,{id,from,to,label});renderEdge(edgeMap.get(id));updateStats()}
function renderEdge(edge){const from=nodeMap.get(edge.from),to=nodeMap.get(edge.to);if(!from||!to)return;const group=document.createElementNS(ns,"g");group.dataset.edgeId=edge.id;const line=document.createElementNS(ns,"line");line.setAttribute("class","edge");line.setAttribute("x1",from.x);line.setAttribute("y1",from.y);line.setAttribute("x2",to.x);line.setAttribute("y2",to.y);const text=document.createElementNS(ns,"text");text.setAttribute("class","edge-label");text.setAttribute("x",(from.x+to.x)/2);text.setAttribute("y",(from.y+to.y)/2-5);text.setAttribute("text-anchor","middle");text.textContent=edge.label;group.append(line,text);edgesLayer.appendChild(group)}
function nodeLabel(node){return node.data.title||node.data.name||"Untitled"}
function renderNode(node){const group=document.createElementNS(ns,"g");group.setAttribute("class",`node ${node.type}`);group.setAttribute("transform",`translate(${node.x} ${node.y})`);group.dataset.nodeId=node.id;const diamond=node.type==="genre"||node.type==="style";if(diamond){const polygon=document.createElementNS(ns,"polygon");polygon.setAttribute("points","0,-28 28,0 0,28 -28,0");group.appendChild(polygon)}else{const circle=document.createElementNS(ns,"circle");circle.setAttribute("r",node.type==="movie"?34:26);group.appendChild(circle)}const imagePath=node.data.poster_path||node.data.profile_path;if(imagePath&&!diamond){const defs=document.createElementNS(ns,"defs"),clip=document.createElementNS(ns,"clipPath"),clipId=`clip-${node.type}-${node.data.id}`;clip.setAttribute("id",clipId);const circle=document.createElementNS(ns,"circle");circle.setAttribute("r",node.type==="movie"?31:23);clip.appendChild(circle);defs.appendChild(clip);const image=document.createElementNS(ns,"image");const size=node.type==="movie"?62:46;image.setAttribute("href",`${IMG}${imagePath}`);image.setAttribute("x",String(-size/2));image.setAttribute("y",String(-size/2));image.setAttribute("width",String(size));image.setAttribute("height",String(size));image.setAttribute("preserveAspectRatio","xMidYMid slice");image.setAttribute("clip-path",`url(#${clipId})`);group.append(defs,image)}const text=document.createElementNS(ns,"text");text.setAttribute("y",node.type==="movie"?52:45);const label=nodeLabel(node);text.textContent=label.length>24?`${label.slice(0,22)}…`:label;group.appendChild(text);group.addEventListener("click",event=>{event.stopPropagation();expandNode(node).catch(showError)});nodesLayer.appendChild(group)}
async function expandNode(node){if(node.type==="movie")return loadMovie(node.data.id,false);if(node.type==="director"||node.type==="actor")return loadPerson(node.data.id,false);if(node.type==="genre")return loadGenre(node.data.id,false);if(node.type==="style")return loadStyle(node.data.id,false)}
function centerOn(nodeId){const node=nodeMap.get(nodeId);if(!node)return;const rect=svg.getBoundingClientRect();scale=Math.min(1.05,Math.max(.55,scale));panX=rect.width/2-node.x*scale;panY=rect.height/2-node.y*scale+55;setTransform()}
function fitMap(){if(!nodeMap.size)return;const values=[...nodeMap.values()],xs=values.map(n=>n.x),ys=values.map(n=>n.y);const minX=Math.min(...xs)-100,maxX=Math.max(...xs)+100,minY=Math.min(...ys)-100,maxY=Math.max(...ys)+100,rect=svg.getBoundingClientRect();scale=Math.min(.95,rect.width/(maxX-minX),rect.height/(maxY-minY));panX=rect.width/2-((minX+maxX)/2)*scale;panY=rect.height/2-((minY+maxY)/2)*scale+40;setTransform()}
async function loadMovie(id,focus=true){errorBox.style.display="none";const data=await getJson(`${API}?id=${encodeURIComponent(id)}`);const root=addNode("movie",data.movie);const additions=[];if(data.director)additions.push({type:"director",data:data.director,label:"directed by"});(data.cast||[]).slice(0,4).forEach(person=>additions.push({type:"actor",data:person,label:"stars"}));data.genres.slice(0,4).forEach(genre=>additions.push({type:"genre",data:genre,label:"genre"}));(data.styles||[]).slice(0,4).forEach(style=>additions.push({type:"style",data:style,label:"theme/style"}));data.related.slice(0,10).forEach((movie,index)=>additions.push({type:"movie",data:movie,label:index<5?"related":"similar"}));additions.forEach((item,index)=>addEdge(root,addNode(item.type,item.data,root,index,additions.length),item.label));showMovieDetails(data);focus?centerOn(root):fitMap()}
async function loadPerson(id,focus=true){const data=await getJson(`${API}?personId=${encodeURIComponent(id)}`);const type=data.type==="director"?"director":"actor";const root=addNode(type,data.person);data.movies.forEach((movie,index)=>addEdge(root,addNode("movie",movie,root,index,data.movies.length),type==="director"?"directed":"performed in"));showCollectionDetails(type==="director"?"Director":"Actor",data.person.name,data.person.biography,data.movies,data.person.profile_path);focus?centerOn(root):fitMap()}
async function loadGenre(id,focus=true){const data=await getJson(`${API}?genreId=${encodeURIComponent(id)}`);const root=addNode("genre",data.genre);data.movies.forEach((movie,index)=>addEdge(root,addNode("movie",movie,root,index,data.movies.length),"genre"));showCollectionDetails("Genre",data.genre.name,`Explore major films associated with ${data.genre.name}.`,data.movies,null);focus?centerOn(root):fitMap()}
async function loadStyle(id,focus=true){const data=await getJson(`${API}?keywordId=${encodeURIComponent(id)}`);const root=addNode("style",data.style);data.movies.forEach((movie,index)=>addEdge(root,addNode("movie",movie,root,index,data.movies.length),"style/theme"));showCollectionDetails("Style / theme",data.style.name,`Explore films connected by the theme, subject, or style “${data.style.name}.”`,data.movies,null);focus?centerOn(root):fitMap()}
function showMovieDetails(data){const movie=data.movie;drawerContent.innerHTML=`<div class="detail-head"><img class="poster" src="${movie.poster_path?`${IMG}${movie.poster_path}`:"mmlogo.png"}" alt="${movie.title}"><div><h2>${movie.title}</h2><div class="meta">${[movie.release_date?.slice(0,4),movie.runtime?`${movie.runtime} min`:"",movie.vote_average?`${movie.vote_average.toFixed(1)}/10`:""].filter(Boolean).join(" · ")}</div>${data.director?`<div class="meta" style="margin-top:6px">Directed by ${data.director.name}</div>`:""}</div></div><p class="overview">${movie.overview||"No overview available."}</p><h3>Explore through</h3><div class="chips">${data.genres.map(g=>`<button data-type="genre" data-id="${g.id}">${g.name}</button>`).join("")}${(data.styles||[]).map(s=>`<button data-type="style" data-id="${s.id}">${s.name}</button>`).join("")}${(data.cast||[]).slice(0,5).map(p=>`<button data-type="actor" data-id="${p.id}">${p.name}</button>`).join("")}</div><h3 style="margin-top:22px">Connected films</h3><div class="chips">${data.related.slice(0,10).map(m=>`<button data-type="movie" data-id="${m.id}">${m.title}</button>`).join("")}</div>`;wireDrawerButtons();drawer.classList.add("open")}
function showCollectionDetails(kind,title,description,movies,imagePath){drawerContent.innerHTML=`<div class="detail-head"><img class="poster" src="${imagePath?`${IMG}${imagePath}`:"mmlogo.png"}" alt="${title}"><div><div class="meta">${kind}</div><h2>${title}</h2><div class="meta">${movies.length} films on this branch</div></div></div><p class="overview">${description||"Explore this branch of cinema."}</p><h3 style="margin-top:22px">Films in this branch</h3><div class="chips">${movies.slice(0,18).map(m=>`<button data-type="movie" data-id="${m.id}">${m.title}</button>`).join("")}</div>`;wireDrawerButtons();drawer.classList.add("open")}
function wireDrawerButtons(){drawerContent.querySelectorAll("button[data-type]").forEach(button=>button.onclick=()=>{const type=button.dataset.type,id=Number(button.dataset.id);if(type==="movie")loadMovie(id,true).catch(showError);if(type==="actor")loadPerson(id,true).catch(showError);if(type==="genre")loadGenre(id,true).catch(showError);if(type==="style")loadStyle(id,true).catch(showError)})}
function iconFor(type){return({movie:"🎬",person:"👤",genre:"🎭",style:"✨"})[type]||"🔗"}
function imageFor(item){return item.image?`${IMG}${item.image}`:""}
function openSearchResult(item){resultsBox.style.display="none";input.value=item.name;if(item.type==="movie")loadMovie(item.id,true).catch(showError);if(item.type==="person")loadPerson(item.id,true).catch(showError);if(item.type==="genre")loadGenre(item.id,true).catch(showError);if(item.type==="style")loadStyle(item.id,true).catch(showError)}
input.addEventListener("input",()=>{clearTimeout(timer);const query=input.value.trim();if(query.length<2)return resultsBox.style.display="none";timer=setTimeout(async()=>{try{const results=await getJson(`${API}?query=${encodeURIComponent(query)}`);resultsBox.innerHTML=results.map((item,index)=>`<div class="result" data-index="${index}">${item.image?`<img src="${imageFor(item)}" alt="">`:`<div class="result-icon">${iconFor(item.type)}</div>`}<div><strong>${item.name}</strong><span>${item.subtitle||item.type}</span></div></div>`).join("");resultsBox.style.display=results.length?"block":"none";resultsBox.querySelectorAll(".result").forEach(row=>row.onclick=()=>openSearchResult(results[Number(row.dataset.index)]))}catch(error){showError(error)}},260)});
function applyFilter(filter){document.querySelectorAll(".filter-chip").forEach(chip=>chip.classList.toggle("active",filter==="all"||chip.dataset.filter===filter||chip.dataset.filter==="all"));nodesLayer.querySelectorAll(".node").forEach(el=>{const show=filter==="all"||el.classList.contains(filter)||el.classList.contains("movie");el.style.opacity=show?"1":".12";el.style.pointerEvents=show?"auto":"none"});edgesLayer.style.opacity=filter==="all"?"1":".38"}
document.querySelectorAll(".filter-chip").forEach(chip=>chip.onclick=()=>applyFilter(chip.dataset.filter));
document.getElementById("closeDrawer").onclick=()=>drawer.classList.remove("open");document.getElementById("fitButton").onclick=fitMap;document.getElementById("resetButton").onclick=()=>{nodeMap.clear();edgeMap.clear();nodesLayer.innerHTML="";edgesLayer.innerHTML="";drawer.classList.remove("open");updateStats();applyFilter("all");loadMovie(603,true).catch(showError)};document.getElementById("randomButton").onclick=async()=>{try{const movie=await getJson(`${API}?random=1&t=${Date.now()}`);if(movie)loadMovie(movie.id,true)}catch(error){showError(error)}};
svg.addEventListener("wheel",event=>{event.preventDefault();const rect=svg.getBoundingClientRect(),mx=event.clientX-rect.left,my=event.clientY-rect.top,oldScale=scale;scale=Math.min(2.4,Math.max(.25,scale*(event.deltaY<0?1.12:.89)));panX=mx-((mx-panX)/oldScale)*scale;panY=my-((my-panY)/oldScale)*scale;setTransform()},{passive:false});svg.addEventListener("pointerdown",event=>{if(event.target.closest?.(".node"))return;dragging=true;activePointerId=event.pointerId;dragStart={x:event.clientX-panX,y:event.clientY-panY};svg.setPointerCapture(event.pointerId);svg.style.cursor="grabbing"});svg.addEventListener("pointermove",event=>{if(!dragging||event.pointerId!==activePointerId)return;panX=event.clientX-dragStart.x;panY=event.clientY-dragStart.y;setTransform()});function endDrag(event){if(!dragging||(activePointerId!==null&&event.pointerId!==activePointerId))return;dragging=false;if(activePointerId!==null&&svg.hasPointerCapture(activePointerId))svg.releasePointerCapture(activePointerId);activePointerId=null;dragStart=null;svg.style.cursor="grab"}svg.addEventListener("pointerup",endDrag);svg.addEventListener("pointercancel",endDrag);window.addEventListener("resize",fitMap);updateStats();loadMovie(603,true).catch(showError);